Q.57] Write a program to calculate PMF and CDF of Binomial distribution with parameters 
n=10, p=0.5


In [ ]:
from scipy.stats import binom
import numpy as np
n = 10
p = 0.5
x = np.arange(0, n+1)
binomial_pmf = binom.pmf(x, n, p)
binomial_pmf


array([0.00097656, 0.00976563, 0.04394531, 0.1171875 , 0.20507813,
       0.24609375, 0.20507813, 0.1171875 , 0.04394531, 0.00976563,
       0.00097656])

In [ ]:
binomial_cdf = binom.cdf(x, n, p)
binomial_cdf

array([9.76562500e-04, 1.07421875e-02, 5.46875000e-02, 1.71875000e-01,
       3.76953125e-01, 6.23046875e-01, 8.28125000e-01, 9.45312500e-01,
       9.89257812e-01, 9.99023438e-01, 1.00000000e+00])

Q.58] Write a program to calculate PMF and CDF of Geometric distribution with parameter 
p=0.5

In [ ]:
from scipy.stats import geom 
Geom_pmf=geom.pmf(p=0.5, k=2)
Geom_pmf

 

0.25

In [ ]:
Geom_cdf=geom.cdf(p=0.5, k=2)
Geom_cdf

0.75

Q59 ] Write a program to calculate and print the mean, median, mode, variance and coefficient 
of variation of the following frequency distribution. 
x 1 2 3 4 5
f 10 20 40 21 9

In [ ]:
X=[1,2,3,4,5]
F=[10,20,40,21,9]
print ("Original list 1 : " + str(X))
print ("Original list 1 : " + str(F))
FX=[]
for i in range(0, len(X)):
    FX.append(X[i]*F[i])
print("FX is :" + str(FX))    


Original list 1 : [1, 2, 3, 4, 5]
Original list 1 : [10, 20, 40, 21, 9]
FX is :[10, 40, 120, 84, 45]


In [ ]:
sum_f=sum(F)
sum_f

100

In [ ]:
sum_fx=sum(FX)
sum_fx

299

Mean

In [ ]:
mean=sum_fx/sum_f
mean

2.99

Median

In [8]:
X=[1,2,3,4,5]
F=[10,20,40,21,9]
x = [1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,5]
med=statistics.median(x)
print("Median of x is % s" % med)


Median of x is 3.0


Mode

In [4]:
import statistics
X = [1,2,3,4,5]
F = [10,20,40,21,9]
MD=max(F)
print("Mode of given data set is % s" % MD)

Mode of given data set is 40


Varience

In [6]:
import statistics
X = [1,2,3,4,5]
F = [10,20,40,21,9]
x = [1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,5]
from statistics import variance
var = variance(x);
print("Variance of X is % s" % var)


Variance of X is 1.1817171717171717


Coefficient of Variation

In [7]:
import numpy as np
import pandas as pd
x = [1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,5]
cv = lambda x: np.std(x, ddof=1) / np.mean(x) * 100 
CV = cv(X)
print("Coefficient of Variation of X is % s" % CV)

Coefficient of Variation of X is 52.70462766947299


Q60 ] Write a program to find the mean, variance and coefficient of variation of n observations. 
Hence find and print the three values for the following set of observations. 
30.1, 23.5, 27.9, 13.4, 15.8, 14.9, 32.4, 35.2, 29.1, 20.1

In [ ]:
import statistics
from statistics import median
X=[30.1,23.5,27.9,13.4,15.8,14.9,32.4,35.2,29.1,20.1]
mean = statistics.mean(X);
median = median(X);
import statistics
from statistics import variance
X = [30.1,23.5,27.9,13.4,15.8,14.9,32.4,35.2,29.1,20.1]
var = variance(X);
import numpy as np
import pandas as pd
cv = lambda x: np.std(x, ddof=1) / np.mean(x) * 100 
CV = cv(X)
print("Mean of X is % s" % mean)
print("Variance of X is % s" % var)
print("Coefficient of Variation of X is % s" % CV)




Mean of X is 24.240000000000002
Variance of X is 61.30266666666667
Coefficient of Variation of X is 32.30033806997643


Q61 ] The lengths and weights of a sample of six articles manufactured by a factor are given 
here.
Length (X) 3 5 6 7 10 11 4 12 13 14
Weight (Y) 8 12 11 14 16 17 10 18 20 21
Write a program to find regression equation of Y on X, correlation coefficient and 
coefficient of determination between n pairs of values of variables X and Y.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

def estimate_coef(x, y):
	# number of observations/points
	n = np.size(x)

	# mean of x and y vector
	m_x = np.mean(x)
	m_y = np.mean(y)

	# calculating cross-deviation and deviation about x
	SS_xy = np.sum(y*x) - n*m_y*m_x
	SS_xx = np.sum(x*x) - n*m_x*m_x

	# calculating regression coefficients
	b_1 = SS_xy / SS_xx
	b_0 = m_y - b_1*m_x

	return (b_0, b_1)

def plot_regression_line(x, y, b):
	# plotting the actual points as scatter plot
	plt.scatter(x, y, color = "m",
			marker = "o", s = 30)

	# predicted response vector
	y_pred = b[0] + b[1]*x

	# plotting the regression line
	plt.plot(x, y_pred, color = "g")

	# putting labels
	plt.xlabel('x')
	plt.ylabel('y')

	# function to show plot
	plt.show()

def main():
	# observations / data
	x = np.array([3,5,6,7,10,11,4,12,13,14])
	y = np.array([8,12,11,14,16,17,10,18,20,21])

	# estimating coefficients
	b = estimate_coef(x, y)
	print("Estimated coefficients:\nb_0 = {} \
		\nb_1 = {}".format(b[0], b[1]))

	if __name__ == "__main__":
	main()


Estimated coefficients:
b_0 = 5.42456140350877 		
b_1 = 1.0912280701754387


correlation coefficient

In [ ]:
X = [3,5,6,7,10,11,4,12,13,14]
Y = [8,12,11,14,16,17,10,18,20,21]
correlation = np.corrcoef(X,Y)
print("The correlation between X and Y is : \n ",correlation)

The correlation between X and Y is : 
  [[1.         0.98724189]
 [0.98724189 1.        ]]


coefficient of determination

In [ ]:
from sklearn.metrics import r2_score 
X = [3,5,6,7,10,11,4,12,13,14]
Y = [8,12,11,14,16,17,10,18,20,21]
R_square = r2_score(X,Y) 
print('Coefficient of Determination', R_square) 

Coefficient of Determination -1.736842105263158


Q63 ] Write a program to arrange a set of n observations in ascending order and find the median. 
Hence arrange the following observations in ascending order and find the median.
26.86, 33.33, 55.82, 10.61, 51.93, 75.94, 61.67, 15.01, 49.17, 76.78

In [ ]:
A = [26.86,33.33,55.82,10.61,51.93,75.94,61.67,15.01,49.17,76.78]
# Python program for implementation of Selection
# Sort
import sys
A = [26.86,33.33,55.82,10.61,51.93,75.94,61.67,15.01,49.17,76.78]

# Traverse through all array elements
for i in range(len(A)):
	
	# Find the minimum element in remaining
	# unsorted array
	min_idx = i
	for j in range(i+1, len(A)):
		if A[min_idx] > A[j]:
			min_idx = j
			
	# Swap the found minimum element with
	# the first element		
	A[i], A[min_idx] = A[min_idx], A[i]

# Driver code to test above
print ("Sorted array")
for i in range(len(A)):
	print("%d" %A[i]),
 

Sorted array
10
15
26
33
49
51
55
61
75
76


In [ ]:
import statistics
A = [26.86,33.33,55.82,10.61,51.93,75.94,61.67,15.01,49.17,76.78]
print("The original list : " + str(A))
  
# Median of list
# Using statistics.median()
res = statistics.median(A)
  
# Printing result
print("Median of list is : " + str(res))

The original list : [26.86, 33.33, 55.82, 10.61, 51.93, 75.94, 61.67, 15.01, 49.17, 76.78]
Median of list is : 50.55


Q64 ] Write a program to arrange a set of n observations in ascending order and find the median. 
Hence arrange the following observations in ascending order and find the median.
18.11, 95.34, 81.31, 36.66, 10.15, 71.81, 3.16, 66.73, 49.03, 79.94

In [ ]:
# Python program for implementation of Selection
# Sort
import sys
A = [18.11,95.34,81.31,36.66,10.15,71.81,3.16,66.73,49.03,79.94]

# Traverse through all array elements
for i in range(len(A)):
	
	# Find the minimum element in remaining
	# unsorted array
	min_idx = i
	for j in range(i+1, len(A)):
		if A[min_idx] > A[j]:
			min_idx = j
			
	# Swap the found minimum element with
	# the first element		
	A[i], A[min_idx] = A[min_idx], A[i]

# Driver code to test above
print ("Sorted array")
for i in range(len(A)):
	print("%d" %A[i]),
 

Sorted array
3
10
18
36
49
66
71
79
81
95


In [ ]:
import statistics
A = [18.11,95.34,81.31,36.66,10.15,71.81,3.16,66.73,49.03,79.94]
print("The original list : " + str(A))
  
# Median of list
# Using statistics.median()
res = statistics.median(A)
  
# Printing result
print("Median of list is : " + str(res))

The original list : [18.11, 95.34, 81.31, 36.66, 10.15, 71.81, 3.16, 66.73, 49.03, 79.94]
Median of list is : 57.88
